app/urls.py
# coding=utf-8

from .views import *
from django.conf.urls import url

__author__ = 'shade'


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^list$', DataListView.as_view(), name='list'),
    url(r'^uploadText$', UploadTextView.as_view(), name='uploadText'),
    url(r'^getText$', GetTextView.as_view(), name='getText'),

]

kvadra_test/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.urls', namespace='app')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
# coding=utf-8

from django.db import models

__author__ = 'shade'



class Data(models.Model):

    fdata = models.TextField('Строка')

app/views.py
# coding=utf-8

from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.list import BaseListView

from app.models import Data
from common.views import JSONResponseMixin, AjaxableCreateMixin

__author__ = 'shade'


class IndexView(TemplateView):

    template_name = 'index.html'

    @method_decorator(ensure_csrf_cookie)
    def dispatch(self, request, *args, **kwargs):
        return super(IndexView, self).dispatch(request, *args, **kwargs)


class DataListView(TemplateView):

    template_name = 'data_list.html'


class UploadTextView(AjaxableCreateMixin):

    model = Data
    fields = ('fdata',)

    def dispatch(self, request, *args, **kwargs):
        return super(UploadTextView, self).dispatch(request, *args, **kwargs)


class GetTextView(JSONResponseMixin, BaseListView):

    model = Data

    def get_data(self, context):

        return [{'fdata': d.fdata, 'id': d.id} for d in context['object_list']]

common/views.py
# coding=utf-8
import json

from django.http.response import JsonResponse
from django.views.generic.edit import CreateView

__author__ = 'shade'


class JSONResponseMixin(object):

    def render_to_json_response(self, context, **response_kwargs):
        return JsonResponse(self.get_data(context), safe=False, **response_kwargs)

    def get_data(self, context):
        raise NotImplementedError

    def render_to_response(self, context):
        return self.render_to_json_response(context)


class AjaxableCreateMixin(CreateView):

    def get_form_kwargs(self):

        kwargs = super(AjaxableCreateMixin, self).get_form_kwargs()
        kwargs.update(json.loads(self.request.body.decode()))

        return kwargs

    def form_invalid(self, form):
        return JsonResponse(form.errors, status=400)

    def form_valid(self, form):
        super(AjaxableCreateMixin, self).form_valid(form)
        return JsonResponse({'created': True})

    def get_success_url(self):
        return '/'

templates/data_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<a href="{% url 'app:index' %}">Добавить строку</a>
<table class="table table-sm table-responsive">
    <thead>
    <tr>
        <th>#</th>
        <th>Строка</th>
    </tr>
    </thead>
    <tbody>

    </tbody>
</table>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.1/underscore-min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script type="text/template" class="template">
    <% _.each(rc, function(item){ %>
    <tr>
        <th scope="row"><%- item.id %></th>
        <td><%- item.fdata %></td>
    </tr>
    <% }); %>
</script>

<script type="application/javascript">

    $(document).ready(function () {

        $.get('getText', function (response) {
            _.templateSettings.variable = "rc";
            var template = _.template($("script.template").html());
            $('tbody').append(template(response))

        })

    })

</script>

</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

<form action="{% url 'app:uploadText' %}" class="data" id="id_form_data">
    <div class="form-group">
        <label for="exampleTextarea">Строка</label>
        <textarea name="fdata" class="form-control" id="id_fdata" cols="30" rows="10"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Отправить</button>
</form>

<br/>
<a href="{% url 'app:list' %}">Смотреть список</a>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="{% static 'js/csrf.js' %}"></script>
<script type="application/javascript">
    $('#id_form_data').submit(function (e) {

        e.preventDefault();
        $.ajax({
            url: $(this).attr('action'),
            type: "POST",
            data: JSON.stringify({"data": {"fdata": $('textarea[name=fdata]').val()}}),
            contentType: "application/json; charset=utf-8",
            dataType: "text",
            success: function (response) {
                $('textarea').val('')
            }
        })
    })

</script>

</body>
</html>